minio:
  servicePreUrl: your service url
  minioEndpoint: your minio endpoint
  minioAccessKey: your minio access key
  minioSecretKey: your minio secret key
  minioBucket: your minio bucket

datasource:
  url: jdbc:mysql://localhost:3306/tus?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf8
  driverClassName: com.mysql.cj.jdbc.Driver
  username: root
  password: 123456
